services:
  - type: web
    name: decode-frontend
    env: static
    buildCommand: cd Frontend && npm install && npm run build
    staticPublishPath: Frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
